GET http://localhost:3000/tes/

### 

GET http://localhost:3000/tes/66d954864626c493be3f2748

###

POST http://localhost:3000/tes/
Content-Type: application/json

{
    "name": "Grandiv",
    "age": 20,
    "birthday": "2000-03-12"
}

###

DELETE http://localhost:3000/tes/66d954864626c493be3f2748

###

PATCH http://localhost:3000/tes/66d954864626c493be3f2748
Content-Type: application/json

{
    "name": "David"
}